
datasource:
  url: jdbc:mysql://webshop.c9t6dmtnqwlu.ap-northeast-2.rds.amazonaws.com:3306/webshop?useSSL=false&serverTimezone=UTC&useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=UTF8
  slave-list:
    - name: slave_1
      url: jdbc:mysql://webshop-slave1.c9t6dmtnqwlu.ap-northeast-2.rds.amazonaws.com:3306/webshop?useSSL=false&serverTimezone=UTC&useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=UTF8
  username: webshop
  password: webshop()

hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect


spring:
  jpa:
    hibernate:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://webshop.c9t6dmtnqwlu.ap-northeast-2.rds.amazonaws.com:3306/board?useSSL=false&serverTimezone=UTC&useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=UTF8
    username: webshop
    password: webshop()
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximum-pool-size: 20

logging:
  level:
    org.springframework.jdbc.datasource.SimpleDriverDataSource: DEBUG
    org.hibernate.SQL: DEBUG
